# Generated by Django 4.1.6 on 2023-03-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
