# Generated by Django 4.1.6 on 2023-03-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='identificacion',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
