# Generated by Django 4.1.6 on 2023-03-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_owner_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='identificacion',
            field=models.CharField(max_length=30),
        ),
    ]
