# Generated by Django 4.1.6 on 2023-02-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment', models.CharField(default='', max_length=100)),
                ('classification', models.CharField(default='', max_length=40)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
